name: Build and run ROS2 tests

on:
  pull_request:
    branches:
      - dev
      - main
      - 'stabilization/**'
  schedule:
    - cron: '0 22 * * *'

jobs:
  build:

    runs-on: wisevision-runner

    continue-on-error: true

    container:
      image: ros:humble-ros-base

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        path: wisevision_data_black_box_ws/src/wisevision_data_black_box
  
    - name: Import repositories using vcs
      run: |
          cd wisevision_data_black_box_ws/src/wisevision_data_black_box
          vcs import --recursive < wisevision_data_black_box.repos
        
    - name: Install dependencies
      run: |
          sudo apt-get update
          sudo apt-get install -y curl libcurl4-openssl-dev libjsoncpp-dev python3-vcstool openssh-client
          if [ ! -f /etc/ros/rosdep/sources.list.d/20-default.list ]; then
            sudo rosdep init
          fi
          sudo rosdep fix-permissions
          rosdep update --include-eol-distros --rosdistro=humble
          cd wisevision_data_black_box_ws
          rosdep install --from-paths src -i -y --rosdistro humble

    - name: Build
      run: |
        . /opt/ros/humble/setup.sh
        cd wisevision_data_black_box_ws
        colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release --packages-up-to wisevision_data_black_box

    - name: Test result summary
      run: |
        . /opt/ros/humble/setup.sh
        cd wisevision_data_black_box_ws
        colcon test --packages-select black_box
        colcon test-result --verbose

    - name: Clean up workspace
      if: always()
      run: |
        sudo rm -rf wisevision_data_black_box_ws